classes: [0, 1, 2, 3, 4]
lth: false
epochs: 25
batch_size: 64
verbose: true
dataset_name: human_activity_recognition
prune_ratio: 0.99
prune_iter: 2
model:
  name: MLP
  activation_fn: ReLU
  input_dim: 561
  hidden_dims: [512, 256]
  dropout: 0
  t: 5.0
optimizer:
  name: Adam
  lr: 0.0001
logger:
  type: Log
    