batch_size: 64
lth: false
classes:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
prune_ratio: 0.99
prune_iter: 2
epochs: 20
dataset_name: mnist
loss_name: MaxEnt #one_vs_all
logger:
  type: Log
model:
  input_dim: 784 
  t: 5.0
  activation_fn: ReLU
  hidden_dims: 
  - 512
  - 256
  dropout: 0.5
  name: MLP
optimizer:
  name: Adam
  lr: 0.001
seeds: 1
verbose: true